apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  # secretName: mypwds
  secretName:
    valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: root_password
  instances: 2
  router:
    instances: 1

  datadirVolumeClaimTemplate:
    storageClassName: vultr-block-storage
    resources:
      requests:
        storage: 10Gi
