# Generate string convert to base64 for store value in data:
# echo -n 'your_password' | base64
# > MTIzcXdl

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  creationTimestamp: null
  name: mysql-secret
data:
  root_password: MTIzcXdl
