apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: mysql-root-password
  instances: 2 # change with your number of nodes
  router:
    instances: 1

  datadirVolumeClaimTemplate:
    storageClassName: vultr-block-storage
    resources:
      requests:
        storage: 10Gi
