apiVersion: pxc.percona.com/v1-11-0
kind: PerconaXtraDBCluster
metadata:
  name: db-cluster
  finalizers:
    - delete-pxc-pods-in-order
spec:
  secretsName: db-cluster-secrets
  crVersion: 1.11.0
  allowUnsafeConfigurations: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: 8.0-recommended
    schedule: "0 4 * * *"
  pxc:
    size: 2
    image: percona/percona-xtradb-cluster:8.0.27-18.1
    autoRecovery: true
    configuration: |
      [mysqld]
      default-time-zone="+07:00"
      max_allowed_packet=1000M
      max_connections=5000
    # resources:
    #   requests:
    #     memory: 1G
    #     cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
#      minAvailable: 0
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: vultr-block-storage
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 11G
    gracePeriod: 600

  haproxy:
    enabled: true
    size: 2
    image: perconalab/percona-xtradb-cluster-operator:main-haproxy
    # resources:
    #   requests:
    #     memory: 1G
    #     cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
#      minAvailable: 0
    gracePeriod: 30


  logcollector:
    enabled: true
    image: perconalab/percona-xtradb-cluster-operator:main-logcollector
    resources:
      requests:
        memory: 100M
        cpu: 200m


# Insert content in backup.yaml below to automatically backup db
